// Command gen-template-quantum embeds the quantum-lab example into
// cmd/ernest/template_quantum.go as interpreted-string constants.
//
// Why a generator? orchestrate.py and scenarios-quantum.json contain
// markdown code fences (```), which are impossible inside Go raw-string
// literals. This script reads the real example files (single source of
// truth) and emits escaped constants that compile.
//
// Run from the repo root:
//
//	go run ./scripts/gen-template-quantum.go
//
// The generated file is committed; regenerate it whenever the example
// changes. The test in cmd/ernest/template_test.go verifies the emitted
// template still scaffolds a valid project.
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
)

const (
	quantumReadme = `# quantum-lab template

A four-agent quantum physics team (ernest.json) plus an orchestrator
(orchestrate.py) that runs real Qiskit experiments and reproduces a
noise + readout-error-mitigation study end to end:

  quantum-theorist  designs the noise experiment + mitigation strategy
  quantum-engineer  writes Qiskit 2.x code (raw run, then mitigated run)
  quantum-analyst   reads REAL execution output (counts, fidelity, error
                    rates) and issues data-driven verdicts
  quantum-reviewer  QA critic (available for review rounds)

Artifacts land in build/: an executed Jupyter notebook
(quantum-lab.ipynb) with real stdout outputs, qiskit_v1.py (raw run)
and qiskit_v2.py (mitigated run).

## Prerequisites

- Go toolchain (builds the ernest binary)
- Python 3.10+ with: pip install ernest qiskit qiskit-aer
- An OpenRouter API key for the four agents

## Run

1. Set your key:
     export OPENROUTER_API_KEY=sk-or-...      (Linux/macOS)
     setx OPENROUTER_API_KEY sk-or-...        (Windows, new shell)
   or copy .env.example to .env and export the line.

2. Build the ernest CLI and boot the playground server on :9293:
     go install github.com/nemo715/Ernest/cmd/ernest@latest
     ernest playground --config ernest.json --port 9293
   (point --static at a built UI export if you have one; omit it for
   the API-only server)

3. Run the orchestrator in a second terminal:
     python orchestrate.py --base-url http://127.0.0.1:9293

4. Watch the agents collaborate: theory, code, real execution, analysis,
   mitigation, final verdict. Open build/quantum-lab.ipynb afterwards.

## Eval

The scenario suite (scenarios-quantum.json) gates the team's behavior:

     ./ernest eval --config ernest.json \
       --scenarios scenarios-quantum.json \
       --json --update-baseline

Re-run with --baseline eval-baseline.json in CI to catch regressions.
`

	quantumEnv = `# Copy to .env and export the line, or set the var directly.
OPENROUTER_API_KEY=
`
)

func main() {
	root := "examples/quantum-lab"
	inputs := []struct {
		path    string
		varName string
		comment string
	}{
		{"ernest.json", "quantumErnestJSON", "the four-agent team config (also used by ernest playground/eval)"},
		{"orchestrate.py", "quantumOrchestratePY", "the Python orchestrator: real Qiskit runs + agent loop"},
		{"scenarios-quantum.json", "quantumScenariosJSON", "eval scenarios gating the team"},
	}

	var out string
	out += "// Code generated by scripts/gen-template-quantum.go; DO NOT EDIT.\n"
	out += "// The quantum template embeds the quantum-lab example (examples/quantum-lab).\n"
	out += "// Regenerate with: go run ./scripts/gen-template-quantum.go\n"
	out += "package main\n\n"
	for _, in := range inputs {
		data, err := os.ReadFile(filepath.Join(root, in.path))
		if err != nil {
			fmt.Fprintf(os.Stderr, "gen: %v\n", err)
			os.Exit(1)
		}
		out += "// " + in.comment + "\n"
		out += "const " + in.varName + " = " + strconv.Quote(string(data)) + "\n\n"
	}
	out += "const quantumReadmeMD = " + strconv.Quote(quantumReadme) + "\n\n"
	out += "const quantumEnvExample = " + strconv.Quote(quantumEnv) + "\n\n"
	out += `func init() {
	newTemplates["quantum"] = struct {
		summary string
		files   map[string]string
	}{
		summary: "quantum physics team: 4 agents + Qiskit orchestrator + eval suite",
		files: map[string]string{
			"ernest.json":            quantumErnestJSON,
			"orchestrate.py":         quantumOrchestratePY,
			"scenarios-quantum.json": quantumScenariosJSON,
			"README.md":              quantumReadmeMD,
			".env.example":           quantumEnvExample,
		},
	}
}
`

	if err := os.WriteFile("cmd/ernest/template_quantum.go", []byte(out), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gen: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("wrote cmd/ernest/template_quantum.go")
}
